# Automatically generated by configure - do not modify!
shared=
build_suffix=
prefix=/home/sunyc/work/audio-effects/xmly-audio-utils/ffmpeg-3.4.7/build
libdir=${prefix}/lib
incdir=${prefix}/include
rpath=
source_path=.
LIBPREF=lib
LIBSUF=.a

extralibs_avutil="  -lm"
extralibs_avcodec="-s USE_SDL=2 -s USE_SDL=2 -lm  "
extralibs_avformat="-s USE_SDL=2 -s USE_SDL=2 -lm  "
extralibs_avdevice="-s USE_SDL=2 -s USE_SDL=2 -lm  "
extralibs_avfilter="-s USE_SDL=2 -s USE_SDL=2 -lm  "
extralibs_avresample="-lm"
extralibs_postproc=""
extralibs_swscale="-lm"
extralibs_swresample="-lm "
avcodec_deps="avutil"
avdevice_deps="avformat avcodec avutil"
avfilter_deps="avutil"
avformat_deps="avcodec avutil"
avresample_deps="avutil"
avutil_deps=""
postproc_deps="avutil"
swresample_deps="avutil"
swscale_deps="avutil"
