
EFFECT(noise_suppression)
EFFECT(beautify)
EFFECT(reverb)
EFFECT(limiter)
EFFECT(minions)
EFFECT(voice_morph)
//sox
EFFECT(compand)
EFFECT(mcompand)
EFFECT(highpass)
EFFECT(lowpass)
EFFECT(bandpass)
EFFECT(bandreject)
EFFECT(allpass)
EFFECT(equalizer)
